import { afterEach, describe, expect, it, vi } from 'vitest'
import { generateClientSeedHex } from './client-fairness'

describe('generateClientSeedHex', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('returns the requested number of cryptographically generated bytes as hex', () => {
    vi.stubGlobal('crypto', {
      getRandomValues: (bytes: Uint8Array) => {
        bytes.set([0x00, 0x7f, 0xa5, 0xff])
        return bytes
      },
    })

    expect(generateClientSeedHex(4)).toBe('007fa5ff')
  })

  it('fails closed when the browser has no secure RNG', () => {
    vi.stubGlobal('crypto', undefined)

    expect(() => generateClientSeedHex()).toThrow('Secure random generation is not available')
  })
})
